-- MySQL Script generated by MySQL Workbench
-- 03/03/15 17:17:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `3380project` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `3380project` ;

-- -----------------------------------------------------
-- Table `3380project`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3380project`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `preferred_name` VARCHAR(50) NOT NULL,
  `middle_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `cell_phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` BLOB NULL,
  `psid` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `psid_UNIQUE` (`psid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3380project`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3380project`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `notes` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3380project`.`centers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3380project`.`centers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `location` VARCHAR(100) NULL,
  `notes` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3380project`.`balls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3380project`.`balls` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `manufacurer_id` INT NULL,
  `data_filepath` VARCHAR(100) NULL,
  `core_symmetric` TINYINT(1) NULL,
  `rg` FLOAT NULL,
  `differential` FLOAT NULL,
  `color` VARCHAR(50) NULL,
  `cover_stock` ENUM('plastic','urethane','reactive_resin','solid_reactive','pearl_reactive','hybrid_reactive','particle') NULL,
  `notes` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3380project`.`pattern`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3380project`.`pattern` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `filepath` VARCHAR(100) NULL,
  `notes` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3380project`.`sets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3380project`.`sets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `center_id` INT NULL,
  `pattern_id` INT NULL,
  `event_id` INT NULL,
  `notes` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `center_idx` (`center_id` ASC),
  INDEX `pattern_idx` (`pattern_id` ASC),
  INDEX `event_idx` (`event_id` ASC),
  CONSTRAINT `center`
    FOREIGN KEY (`center_id`)
    REFERENCES `3380project`.`centers` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `pattern`
    FOREIGN KEY (`pattern_id`)
    REFERENCES `3380project`.`pattern` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `event`
    FOREIGN KEY (`event_id`)
    REFERENCES `3380project`.`events` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3380project`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3380project`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `set_id` INT NULL,
  `game_number` INT NOT NULL,
  `time_bowled` TIMESTAMP NULL,
  `baker` TINYINT(1) NOT NULL,
  `user_id` INT NULL,
  `scrore` INT NULL,
  `notes` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `set_idx` (`set_id` ASC),
  INDEX `user_idx` (`user_id` ASC),
  CONSTRAINT `set`
    FOREIGN KEY (`set_id`)
    REFERENCES `3380project`.`sets` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `user2`
    FOREIGN KEY (`user_id`)
    REFERENCES `3380project`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3380project`.`surface_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3380project`.`surface_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `notes` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3380project`.`balls_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3380project`.`balls_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ball_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `drill_pattern_filename` VARCHAR(100) NULL,
  `custom_name` VARCHAR(50) NULL,
  `surface_type_id` INT NULL,
  `pearlized` TINYINT(1) NULL,
  `notes` TEXT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `ball_id`),
  INDEX `surface_idx` (`surface_type_id` ASC),
  INDEX `ball_idx` (`ball_id` ASC),
  INDEX `user_idx` (`user_id` ASC),
  CONSTRAINT `surface`
    FOREIGN KEY (`surface_type_id`)
    REFERENCES `3380project`.`surface_types` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `ball`
    FOREIGN KEY (`ball_id`)
    REFERENCES `3380project`.`balls` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `user`
    FOREIGN KEY (`user_id`)
    REFERENCES `3380project`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3380project`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3380project`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `owner_id` INT NOT NULL,
  `notes` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_idx` (`owner_id` ASC),
  CONSTRAINT `users`
    FOREIGN KEY (`owner_id`)
    REFERENCES `3380project`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3380project`.`frames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3380project`.`frames` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `game_id` INT NULL,
  `user_id` INT NOT NULL,
  `lane` INT NULL,
  `frame_number` INT NULL,
  `center_id` INT NULL,
  `pattern_id` INT NULL,
  `timestamp` TIMESTAMP NULL,
  `b1_ball_id` INT NULL,
  `b1_release` ENUM('left_3_finger','right_3_finger','left_2_finger','right_2_finger','left_2_hand','right_2_hand') NULL,
  `b1_gutter` TINYINT(1) NULL,
  `b1_foul` TINYINT(1) NULL,
  `b1_p1` TINYINT(1) NOT NULL,
  `b1_p2` TINYINT(1) NOT NULL,
  `b1_p3` TINYINT(1) NOT NULL,
  `b1_p4` TINYINT(1) NOT NULL,
  `b1_p5` TINYINT(1) NOT NULL,
  `b1_p6` TINYINT(1) NOT NULL,
  `b1_p7` TINYINT(1) NOT NULL,
  `b1_p8` TINYINT(1) NOT NULL,
  `b1_p9` TINYINT(1) NOT NULL,
  `b1_p10` TINYINT(1) NOT NULL,
  `b2_ball_id` INT NULL,
  `b2_release` ENUM('left_3_finger','right_3_finger','left_2_finger','right_2_finger','left_2_hand','right_2_hand') NULL,
  `b2_gutter` TINYINT(1) NULL,
  `b2_foul` TINYINT(1) NULL,
  `b2_p1` TINYINT(1) NULL,
  `b2_p2` TINYINT(1) NULL,
  `b2_p3` TINYINT(1) NULL,
  `b2_p4` TINYINT(1) NULL,
  `b2_p5` TINYINT(1) NULL,
  `b2_p6` TINYINT(1) NULL,
  `b2_p7` TINYINT(1) NULL,
  `b2_p8` TINYINT(1) NULL,
  `b2_p9` TINYINT(1) NULL,
  `b2_p10` TINYINT(1) NULL,
  `b3_ball_id` INT NULL,
  `b3_release` ENUM('left_3_finger','right_3_finger','left_2_finger','right_2_finger','left_2_hand','right_2_hand') NULL,
  `b3_gutter` TINYINT(1) NULL,
  `b3_foul` TINYINT(1) NULL,
  `b3_p1` TINYINT(1) NULL,
  `b3_p2` TINYINT(1) NULL,
  `b3_p3` TINYINT(1) NULL,
  `b3_p4` TINYINT(1) NULL,
  `b3_p5` TINYINT(1) NULL,
  `b3_p6` TINYINT(1) NULL,
  `b3_p7` TINYINT(1) NULL,
  `b3_p8` TINYINT(1) NULL,
  `b3_p9` TINYINT(1) NULL,
  `b3_p10` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `game_idx` (`game_id` ASC),
  INDEX `center_idx` (`center_id` ASC),
  INDEX `pattern_idx` (`pattern_id` ASC),
  INDEX `ball1_idx` (`b1_ball_id` ASC),
  INDEX `ball2_idx` (`b2_ball_id` ASC),
  INDEX `ball3_idx` (`b3_ball_id` ASC),
  CONSTRAINT `user3`
    FOREIGN KEY (`user_id`)
    REFERENCES `3380project`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `3380project`.`games` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `center1`
    FOREIGN KEY (`center_id`)
    REFERENCES `3380project`.`centers` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `pattern1`
    FOREIGN KEY (`pattern_id`)
    REFERENCES `3380project`.`pattern` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `ball1`
    FOREIGN KEY (`b1_ball_id`)
    REFERENCES `3380project`.`balls_users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `ball2`
    FOREIGN KEY (`b2_ball_id`)
    REFERENCES `3380project`.`balls_users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `ball3`
    FOREIGN KEY (`b3_ball_id`)
    REFERENCES `3380project`.`balls_users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `3380project`.`teams_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `3380project`.`teams_users` (
  `team_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`team_id`, `user_id`),
  INDEX `user_idx` (`user_id` ASC),
  CONSTRAINT `team3`
    FOREIGN KEY (`team_id`)
    REFERENCES `3380project`.`teams` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `user3`
    FOREIGN KEY (`user_id`)
    REFERENCES `3380project`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
